# Generated by Django 4.1.3 on 2022-12-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_munu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='munu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='메뉴'),
        ),
    ]
