# Generated by Django 4.1.3 on 2022-12-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='public',
        ),
    ]
